// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDcUMtvV9Bx9DiiuTk2iZKNgjOp0E9H0E',
    appId: '1:6268455203:web:99ba8df4ee136436a92496',
    messagingSenderId: '6268455203',
    projectId: 'studygroup-1850c',
    authDomain: 'studygroup-1850c.firebaseapp.com',
    storageBucket: 'studygroup-1850c.appspot.com',
    measurementId: 'G-J6BV1M6WH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFr7OGm88PHsaCHerW7V04IGuPNwA1PMU',
    appId: '1:6268455203:android:837ed91a9bef11f7a92496',
    messagingSenderId: '6268455203',
    projectId: 'studygroup-1850c',
    storageBucket: 'studygroup-1850c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVd7qSoIFTwXa78I3n0XN5QyGr61QSDRU',
    appId: '1:6268455203:ios:1c6749f2634121f3a92496',
    messagingSenderId: '6268455203',
    projectId: 'studygroup-1850c',
    storageBucket: 'studygroup-1850c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVd7qSoIFTwXa78I3n0XN5QyGr61QSDRU',
    appId: '1:6268455203:ios:d1397eef7e57b7ffa92496',
    messagingSenderId: '6268455203',
    projectId: 'studygroup-1850c',
    storageBucket: 'studygroup-1850c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
